/*
 * XDSAUno.idl
 *
 * Created on 2010.03.10 - 14:08:37
 *
 */

#ifndef __alma_scheduling_XDSAUno__
#define __alma_scheduling_XDSAUno__

#include <com/sun/star/uno/XInterface.idl>

module alma { module scheduling {
    interface XDSAUno {

        void load();

        void run();
    };
}; };

#endif
