#! /bin/bash

#Set my CDB
export ACS_CDB=`pwd`
# for archive...
export CLASSPATH=$CLASSPATH:$ACSROOT/lib/oracle/xmlparserv2.jar 
#Start ACS & the Manager
acsStart >& sched_acsStart.log

#Get the instance which ACS started on
export ACS_INSTANCE=`grep -m 1 "For this ACS session, please do an" sched_acsStart.log | cut -d\' -f2 | cut -d= -f2`

#Save the instance var to a file for easy access
echo $ACS_INSTANCE > sched_acs_instance.log

acsStartContainer -java java >& test.log &
tomcat start 
#if [ $? ]; then echo "Executing Conditional branch"; else echo "hmm"; fi
#echo "foo"
#Start a java container named 'java'
acsStartContainer -java ACC/javaContainer >& sched_javaContainer.log &
acsStartContainer -cpp ACC/cppContainer >& sched_cppContainer.log &
acsStartContainer -java ACC/masterContainer >& sched_masterContainer.log &
#Start a java container for the archive
acsStartContainer -java ARCHIVE/ACC/javaContainer >& sched_archiveContainer.log &
#Start a python container named 'python'
acsStartContainer -py CONTROL/ACC/pythonContainer >& sched_pythonContainer.log &

sleep 15
