#! /bin/bash
#just double check a left over ShutdwonAllowed isn't there
#rm ShutdownAllowed
#Set Native ssh so omc works properly
export JAVA_OPTIONS="$JAVA_OPTIONS -DAcsCommandCenter.useNativeSSH=true -DAcsCommandCenter.killNativeSSH=true"
#Startup the OMC and initialize the ALMA MCs
operatormasterclient ExecConfigOP.xml SchedulingPolicyOP.xml AcsProjectOP.xml -- -b alma.scheduling.test.OpticalPointingStartup &> omc.log &

waitfor=acsStartedByOMC
waitmax=300
i=0 ; while [ true ] ; do
  if [ -e $waitfor ] ; then rm $waitfor ; break; fi
  if [ $i == $waitmax ] ; then echo "Takes too long!" ; break; fi
  sleep 1 ; let i=i+1
done 

archiveStart &> archiveStart.log
#archiveCleanTest &> archiveClean.log
#archiveLoadSchema $ACSROOT/idl &> archiveLoadSchema.log
