#! /bin/bash
# create the file that tells the OMC batch sequence script to stop
# if you change the name of this file you need to change it in the 
# class that runs the batch sequence
#archiveCleanTest
touch ShutdownAllowed
#allow a while for ACS to stop
sleep 30
#delete the file above
rm ShutdownAllowed
waitfor=acsStoppedByOMC
waitmax=300
i=0 ; while [ true ] ; do
  if [ -e $waitfor ] ; then rm $waitfor ; break; fi
  if [ $i == $waitmax ] ; then echo "Takes too long!" ; break; fi
  sleep 1 ; let i=i+1
done
#rm acsStartedByOMC
#rm acsStoppedByOMC

