#!/bin/bash

# Use any arguments as the projects to load. If there are no 
# arguments load them all
if [[ $# == 0 ]]
then
   subsystems=(projects/*.aot)
else
   subsystems=($@)
fi
export JAVA_OPTIONS="-Dot.submission.host=http://127.0.0.1:8180 -Dot.submission.user=john -Dot.submission.pass=john -Dalma.obsprep.allowprivileged=true $JAVA_OPTIONS"
ALMA-OT -batch scripts/bulk-import-saveasnew-retrieve.py ${subsystems[@]}

