#!/bin/bash

# Use any arguments as the projects to load. If there are no 
# arguments load them all
if [[ $# == 0 ]]
then
   subsystems=(projects/*.aot)
else
   subsystems=($@)
fi
JAVA_OPTIONS="-Dalma.obsprep.allowprivileged=true $JAVA_OPTIONS"
ALMA-OT -batch scripts/bulk-import-saveasnew-retrieve.py ${subsystems[@]}

