#!/bin/bash

# We require the config/testenv file.
[ -f config/testEnv ] || exit $?

# Source test configuration file. 
. config/testEnv

if test -a $ACSROOT/lib/sqltool.jar; then
    HSQLDB_JAR=$ACSROOT/lib/sqltool.jar
elif test -a $INTROOT/lib/sqltool.jar; then
    HSQLDB_JAR=$INTROOT/lib/sqltool.jar
fi

if test $# -ge 1; then
   SQL_COMMAND=$@
fi

if test -n "$SQL_COMMAND"; then
    java -jar "$HSQLDB_JAR" --rcFile "$SQLTOOL_RC_FILE" --sql "$SQL_COMMAND" "$DBNAME"
else
    java -jar "$HSQLDB_JAR" --rcFile "$SQLTOOL_RC_FILE" "$DBNAME"
fi

