/*
 * ddl for the state archive -- hypersonic sql version
 * amchavan, 18-jun-2009, creation
 *
 * $id: hsqldb-ddl.sql,v 1.2.2.3 2009/09/01 12:14:17 rkurowsk exp $ 
 */
 
drop table obs_project_status  if exists;
drop table obs_unit_set_status if exists;
drop table sched_block_status  if exists;
drop table state_changes  if exists;

create table public.obs_project_status ( 

    status_entity_id char(64)              not null, 
    domain_entity_id char(64)              not null, 
    domain_entity_state char(32)           not null,
    obs_project_status_id char(64)         not null,
    obs_program_status_id char(64)             null,  
    obs_project_id char(64)                not null, 
	project_was_timed_out datetime             null,
    xml longvarchar                        not null,
    primary key(status_entity_id)
);

create table public.obs_unit_set_status ( 

    status_entity_id char(64)              not null, 
    domain_entity_id char(64)                  null, 
    domain_entity_state char(32)           not null,
    parent_obs_unit_set_status_id char(64)     null,
    obs_project_status_id char(64)         not null, 
    obs_project_id char(64)                not null, 
    total_required_time_in_sec integer     not null,
    total_used_time_in_sec integer         not null,   
    xml longvarchar                        not null,

    primary key(status_entity_id) 
);

create table public.sched_block_status ( 
    status_entity_id char(64)              not null, 
    domain_entity_id char(64)              not null, 
    domain_entity_state char(32)           not null, 
    parent_obs_unit_set_status_id char(64) not null, 
    obs_project_status_id char(64)         not null, 
    obs_project_id char(64)                not null, 
    total_required_time_in_sec integer     not null,
    total_used_time_in_sec integer         not null,
    xml longvarchar                        not null,

    primary key(status_entity_id)  
);

create table public.state_changes ( 
    state_changes_id bigint generated by default as identity (start with 1),
    status_entity_id char(64)              not null, 
    domain_entity_id char(64)              not null,
    domain_part_id char(64)              	   null,    
    domain_entity_state char(32)           not null,
    timestamp datetime                     not null,
    location char(3)                       not null,
    user_id char(64)                       not null,
    subsystem char(32)                     not null,
    info char(64)                          null,
    entity_type char(3)                    not null
);
