/*
 * ALMA - Atacama Large Millimeter Array
 * (c) European Southern Observatory, 2002
 * (c) Associated Universities Inc., 2002
 * Copyright by ESO (in the framework of the ALMA collaboration),
 * Copyright by AUI (in the framework of the ALMA collaboration),
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307  USA
 *
 * $Id: SchedulingMaster.idl,v 1.3 2011/01/28 00:35:37 javarias Exp $
 */

#ifndef _SCHEDULINGMASTER_IDL_
#define _SCHEDULINGMASTER_IDL_

#include <acscomponent.idl>
#include <SchedulingMasterExceptions.idl>
#include <SchedulingArray.idl>
#include <ControlInterfaces.idl>

#pragma prefix "alma"

module scheduling {

    typedef string ArrayIdentifier;
	typedef sequence<ArrayIdentifier> ArrayIdentifierSeq;
    typedef Control::AntennaId AntennaId;
    typedef sequence<Control::AntennaId> AntennaIdSeq;    
    typedef Control::ResourceNameSeq PhotonicsSeq;
    enum ArrayModeEnum { DYNAMIC, INTERACTIVE, QUEUED, MANUAL };
    
    struct ArrayCreationInfo {
        ArrayIdentifier arrayId;
        string arrayComponentName;
    };

    interface Master : ACS::ACSComponent {
        ArrayCreationInfo createArray(in AntennaIdSeq antennaIdList,
                              in PhotonicsSeq photonicsList,
                              in Control::CorrelatorType corrType,
                              in ArrayModeEnum schedulingMode,
                              in ArraySchedulerLifecycleType lifecycleType) 
			raises (SchedulingMasterExceptions::ControlInternalExceptionEx,
					SchedulingMasterExceptions::SchedulingInternalExceptionEx, 
					SchedulingMasterExceptions::ACSInternalExceptionEx);

        void destroyArray(in ArrayIdentifier arrayId) raises 
			(SchedulingMasterExceptions::ControlInternalExceptionEx,
			 SchedulingMasterExceptions::SchedulingInternalExceptionEx, 
			 SchedulingMasterExceptions::ACSInternalExceptionEx);
		
		ArrayIdentifierSeq getActiveAutomaticArrays();

		ArrayIdentifierSeq getActiveManualArrays();

		ArrayModeEnum getSchedulerModeForArray(in string arrayName) raises (SchedulingMasterExceptions::ArrayNotFoundExceptionEx);

    };

};
#endif // _SCHEDULINGMASTER_IDL_
