#! /bin/bash

# Shutdown acs and java processes

acsStopContainer Activator >&  /dev/null
acsStopContainer hugoActivator >&  /dev/null
maciManagerShutdown >&  /dev/null
acsStopORBSRVC >&  /dev/null
#killall java
