#! /bin/bash

# Shutdown acs and java processes

#killACS
#acsStopContainer Activator >&  /dev/null
acsStopContainer frodoContainer -b0 >&  /dev/null
maciManagerShutdown -b0 >&  /dev/null
acsStopORBSRVC -b0 >&  /dev/null
acsdataClean
