#! /bin/bash

# Get required paths
ACS_CDB=$PWD


# Start acs processes
echo " Cleaning acsdata"
acsdataClean >& /dev/null &

echo " Starting ORB Services"
#acsStartORBSRVC >& /dev/null &
acsStartORBSRVC >& sched_orbsrvc.log 

sleep 35

echo " Starting Manager"
maciManagerJ -m >& sched_manager.log&
sleep 30

echo " Starting Activator"
maciActivate Activator  >& sched_activator.log&
sleep 15

echo " Starting hugoActivator"
acsStartContainer hugoActivator >& sched_hugoActivator.log &
sleep 20

