#! /bin/bash

# Get required paths
ACS_CDB=$PWD


# Start acs processes
echo " Starting ORB Services"
acsStartORBSRVC >& /dev/null &
sleep 60

echo " Starting Manager"
maciManagerJ >& /dev/null&
sleep 20

echo " Starting hugoActivator"
acsStartContainer hugoActivator >& /dev/null &
sleep 5

