#! /bin/bash

# Get required paths
ACS_CDB=$PWD


# Start acs processes
echo " Cleaning acsdata"
acsdataClean >& /dev/null &

echo " Starting ORB Services"
acsStartORBSRVC >& /dev/null &
sleep 30

echo " Starting Manager"
maciManagerJ >& /dev/null&
sleep 30

##echo " Starting hugoActivator"
##acsStartContainer hugoActivator >& /dev/null &
##sleep 5

