#! /bin/bash

# Run test
#echo " Starting Activator"
maciActivate Activator &
sleep 10

#echo " Starting Container"
acsStartContainer hugoActivator &
sleep 10

#echo " Running almaOTBatchMode"
almaOTBatchMode.sh targets.txt
sleep 10

#echo " Running test"
abeansStart -endorsed ALMA.scheduling.test.SchedTest7

maciActivatorShutdown Activator >& /dev/null
acsStopContainer hugoActivator >&  /dev/null

