#! /bin/bash

export ACS_INSTANCE=`cat sched_acs_instance`

archiveCleanMA

archiveLoadSchema

otprotoBatch targets.txt  >&  sched_almaOT.log

acsStartJava -endorsed alma.scheduling.test.SchedSystemTest

