#! /bin/bash

if [[ $# == 0 ]]
then # No arguments, update everything
   projects=(*.aot)
else # Arguments, assumed to be a list of projects to unpack
   projects=($@)
fi

for z in ${projects[@]}
do
   d=${z/.aot/}
   unzip -d $d $z
done


